version: '3'

services:
    redis-service: #also try build ./source
        image: "redis"
    creator:
        build: "./mtf-create"
        depends_on: 
            - redis-service
        ports:
            - '5000:5000'
    viewer:
        build: "./mtf-viewer"
        depends_on:
            - redis-service
        ports:
            - '5001:5000'

